# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :sputnik do |sputnik|
    sputnik.vm.box = 'centos/7'
    sputnik.vm.hostname = 'sputnik'

    sputnik.vm.network :private_network, ip: "192.168.10.10"
    sputnik.vm.network "forwarded_port", guest: 80, host: 8080

    sputnik.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end

    sputnik.vm.synced_folder "./puppet", "/puppet",
                             type: "rsync"

    sputnik.vm.synced_folder "../queries", "/queries",
                             type: "rsync"

    # Sources for the the action done by the script
    # https://puppet.com/docs/puppet/5.5/install_linux.html
    # https://osquery.readthedocs.io/en/stable/installation/install-linux/

    $provisioning_script = <<SCRIPT
echo Machine wird provisioniert

# Add the repositories for Puppet and OSQuery to yum
rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm

yum makecache

yum install -y puppet-agent
yum install -y osquery
yum install -y emacs-nox
yum install -y psmisc
yum install -y tree
yum install -y httpd
yum install -y net-tools

systemctl enable httpd
systemctl start httpd
systemctl enable osqueryd
systemctl start osqueryd

/opt/puppetlabs/bin/puppet apply /puppet/manifests/sputnik.pp
SCRIPT

    sputnik.vm.provision "shell", inline: $provisioning_script
  end

end


# end of file ;-)

